<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quote;

class OrthodoxQuotesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $quotes = [
            [
                'quote_en' => 'The way of the Lord is a cross, but it leads to resurrection.',
                'quote_fr' => 'La voie du Seigneur est une croix, mais elle mène à la résurrection.',
                'quote_sr' => 'Put Gospodnji je krst, ali vodi ka vaskrsenju.',
                'author_en' => 'John Chrysostom',
                'author_fr' => 'Jean Chrysostome',
                'author_sr' => 'Jovan Zlatousti',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Homily on the Cross',
                'source_fr' => 'Homélie sur la Croix',
                'source_sr' => 'Propoved o krstu',
                'century' => 4,
                'category' => 'spiritual',
                'display_order' => 1,
            ],
            [
                'quote_en' => 'Prayer is the mother and daughter of tears.',
                'quote_fr' => 'La prière est la mère et la fille des larmes.',
                'quote_sr' => 'Molitva je majka i kći suza.',
                'author_en' => 'Isaac of Nineveh',
                'author_fr' => 'Isaac de Ninive',
                'author_sr' => 'Isaak Ninivski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Ascetical Homilies',
                'source_fr' => 'Homélies Ascétiques',
                'source_sr' => 'Pustinjske propovedi',
                'century' => 7,
                'category' => 'prayer',
                'display_order' => 2,
            ],
            [
                'quote_en' => 'God became man so that man might become god.',
                'quote_fr' => 'Dieu s\'est fait homme pour que l\'homme puisse devenir dieu.',
                'quote_sr' => 'Bog je postao čovek da bi čovek postao bog.',
                'author_en' => 'Athanasius of Alexandria',
                'author_fr' => 'Athanase d\'Alexandrie',
                'author_sr' => 'Atanasije Aleksandrijski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'On the Incarnation',
                'source_fr' => 'Sur l\'Incarnation',
                'source_sr' => 'O utelovljenju',
                'century' => 4,
                'category' => 'theology',
                'display_order' => 3,
            ],
            [
                'quote_en' => 'The heart that loves God is never far from Him.',
                'quote_fr' => 'Le cœur qui aime Dieu n\'est jamais loin de Lui.',
                'quote_sr' => 'Srce koje ljubi Boga nikad nije daleko od Njega.',
                'author_en' => 'Seraphim of Sarov',
                'author_fr' => 'Séraphin de Sarov',
                'author_sr' => 'Serafim Sarovski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Spiritual Instructions',
                'source_fr' => 'Instructions Spirituelles',
                'source_sr' => 'Duhovne pouke',
                'century' => 19,
                'category' => 'spiritual',
                'display_order' => 4,
            ],
            [
                'quote_en' => 'Acquire the Spirit of Peace and a thousand souls around you will be saved.',
                'quote_fr' => 'Acquiers l\'Esprit de Paix et mille âmes autour de toi seront sauvées.',
                'quote_sr' => 'Stekni Duha mira i hiljadu duša oko tebe će biti spašeno.',
                'author_en' => 'Seraphim of Sarov',
                'author_fr' => 'Séraphin de Sarov',
                'author_sr' => 'Serafim Sarovski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Conversation with Motovilov',
                'source_fr' => 'Conversation avec Motovilov',
                'source_sr' => 'Razgovor sa Motovilovim',
                'century' => 19,
                'category' => 'spiritual',
                'display_order' => 5,
            ],
            [
                'quote_en' => 'The Church is not a museum of saints, but a hospital for sinners.',
                'quote_fr' => 'L\'Église n\'est pas un musée de saints, mais un hôpital pour pécheurs.',
                'quote_sr' => 'Crkva nije muzej svetaca, već bolnica za grešnike.',
                'author_en' => 'John Chrysostom',
                'author_fr' => 'Jean Chrysostome',
                'author_sr' => 'Jovan Zlatousti',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Homilies on the Gospel',
                'source_fr' => 'Homélies sur l\'Évangile',
                'source_sr' => 'Propovedi o Jevanđelju',
                'century' => 4,
                'category' => 'pastoral',
                'display_order' => 6,
            ],
            [
                'quote_en' => 'The true fast is the estrangement from evil, temperance of tongue, abstinence from anger, separation from desires, slander, falsehood and perjury.',
                'quote_fr' => 'Le vrai jeûne est l\'éloignement du mal, la tempérance de la langue, l\'abstinence de la colère, la séparation des désirs, de la calomnie, du mensonge et du parjure.',
                'quote_sr' => 'Pravi post je udaljavanje od zla, umerenost jezika, uzdržavanje od gneva, odvajanje od želja, klevete, laži i krivokletstva.',
                'author_en' => 'Basil the Great',
                'author_fr' => 'Basile le Grand',
                'author_sr' => 'Vasilije Veliki',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'On Fasting',
                'source_fr' => 'Sur le Jeûne',
                'source_sr' => 'O postu',
                'century' => 4,
                'category' => 'spiritual',
                'display_order' => 7,
            ],
            [
                'quote_en' => 'The soul that loves God has its rest in God and in God alone.',
                'quote_fr' => 'L\'âme qui aime Dieu trouve son repos en Dieu et en Dieu seul.',
                'quote_sr' => 'Duša koja ljubi Boga nalazi svoj mir u Bogu i samo u Bogu.',
                'author_en' => 'Gregory of Nyssa',
                'author_fr' => 'Grégoire de Nysse',
                'author_sr' => 'Grigorije Nisijski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'On the Soul and Resurrection',
                'source_fr' => 'Sur l\'Âme et la Résurrection',
                'source_sr' => 'O duši i vaskrsenju',
                'century' => 4,
                'category' => 'spiritual',
                'display_order' => 8,
            ],
            [
                'quote_en' => 'The greatest of all miracles is a pure heart.',
                'quote_fr' => 'Le plus grand de tous les miracles est un cœur pur.',
                'quote_sr' => 'Najveće od svih čuda je čisto srce.',
                'author_en' => 'Anthony the Great',
                'author_fr' => 'Antoine le Grand',
                'author_sr' => 'Antonije Veliki',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Sayings of the Desert Fathers',
                'source_fr' => 'Dits des Pères du Désert',
                'source_sr' => 'Izreke pustinjskih otaca',
                'century' => 4,
                'category' => 'spiritual',
                'display_order' => 9,
            ],
            [
                'quote_en' => 'The Church is the Body of Christ, and Christ is the Head of the Church.',
                'quote_fr' => 'L\'Église est le Corps du Christ, et le Christ est la Tête de l\'Église.',
                'quote_sr' => 'Crkva je Telo Hristovo, a Hristos je Glava Crkve.',
                'author_en' => 'Paul the Apostle',
                'author_fr' => 'Paul l\'Apôtre',
                'author_sr' => 'Pavle Apostol',
                'title_en' => 'Apostle',
                'title_fr' => 'Apôtre',
                'title_sr' => 'Apostol',
                'source_en' => 'Ephesians 5:23',
                'source_fr' => 'Éphésiens 5:23',
                'source_sr' => 'Efescima 5:23',
                'century' => 1,
                'category' => 'theology',
                'display_order' => 10,
            ],
            [
                'quote_en' => 'The Lord is my shepherd; I shall not want. He makes me lie down in green pastures.',
                'quote_fr' => 'L\'Éternel est mon berger; je ne manquerai de rien. Il me fait reposer dans de verts pâturages.',
                'quote_sr' => 'Gospod je moj pastir; neću oskudevati. Čini da se spuštam u zelenim pašnjacima.',
                'author_en' => 'David',
                'author_fr' => 'David',
                'author_sr' => 'David',
                'title_en' => 'King and Prophet',
                'title_fr' => 'Roi et Prophète',
                'title_sr' => 'Kralj i Prorok',
                'source_en' => 'Psalm 23:1-2',
                'source_fr' => 'Psaume 23:1-2',
                'source_sr' => 'Psalam 23:1-2',
                'century' => -10,
                'category' => 'prayer',
                'display_order' => 11,
            ],
            [
                'quote_en' => 'Theosis is the purpose of human life.',
                'quote_fr' => 'La théosis est le but de la vie humaine.',
                'quote_sr' => 'Teoza je svrha ljudskog života.',
                'author_en' => 'Vladimir Lossky',
                'author_fr' => 'Vladimir Lossky',
                'author_sr' => 'Vladimir Loski',
                'title_en' => 'Theologian',
                'title_fr' => 'Théologien',
                'title_sr' => 'Teolog',
                'source_en' => 'The Mystical Theology of the Eastern Church',
                'source_fr' => 'La Théologie Mystique de l\'Église d\'Orient',
                'source_sr' => 'Mistička teologija istočne crkve',
                'century' => 20,
                'category' => 'theology',
                'display_order' => 12,
            ],
            [
                'quote_en' => 'Pray without ceasing.',
                'quote_fr' => 'Priez sans cesse.',
                'quote_sr' => 'Molite se neprestano.',
                'author_en' => 'Paul the Apostle',
                'author_fr' => 'Paul l\'Apôtre',
                'author_sr' => 'Pavle Apostol',
                'title_en' => 'Apostle',
                'title_fr' => 'Apôtre',
                'title_sr' => 'Apostol',
                'source_en' => '1 Thessalonians 5:17',
                'source_fr' => '1 Thessaloniciens 5:17',
                'source_sr' => '1. Solunjanima 5:17',
                'century' => 1,
                'category' => 'prayer',
                'display_order' => 13,
            ],
            [
                'quote_en' => 'The glory of God is man fully alive.',
                'quote_fr' => 'La gloire de Dieu, c\'est l\'homme pleinement vivant.',
                'quote_sr' => 'Slava Boga je čovek potpuno živ.',
                'author_en' => 'Irenaeus of Lyons',
                'author_fr' => 'Irénée de Lyon',
                'author_sr' => 'Irenej Lionski',
                'title_en' => 'Saint',
                'title_fr' => 'Saint',
                'title_sr' => 'Sveti',
                'source_en' => 'Against Heresies',
                'source_fr' => 'Contre les Hérésies',
                'source_sr' => 'Protiv jeresi',
                'century' => 2,
                'category' => 'theology',
                'display_order' => 14,
            ],
            [
                'quote_en' => 'Love is the fulfillment of the law.',
                'quote_fr' => 'L\'amour est l\'accomplissement de la loi.',
                'quote_sr' => 'Ljubav je ispunjenje zakona.',
                'author_en' => 'Paul the Apostle',
                'author_fr' => 'Paul l\'Apôtre',
                'author_sr' => 'Pavle Apostol',
                'title_en' => 'Apostle',
                'title_fr' => 'Apôtre',
                'title_sr' => 'Apostol',
                'source_en' => 'Romans 13:10',
                'source_fr' => 'Romains 13:10',
                'source_sr' => 'Rimljanima 13:10',
                'century' => 1,
                'category' => 'spiritual',
                'display_order' => 15,
            ],
        ];

        foreach ($quotes as $quote) {
            Quote::create($quote);
        }
    }
}