<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PrayerRequest;

class PrayerRequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $prayerRequests = [
            [
                'title' => 'Healing for Maria',
                'request' => 'Please pray for my grandmother Maria who is recovering from surgery. May God grant her strength and healing.',
                'requester_name' => 'Anna Petrov',
                'requester_email' => 'anna.petrov@email.com',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'health',
                'prayer_count' => 12,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Family Reunion',
                'request' => 'Praying for my family to come together in peace and harmony. We have been struggling with conflicts and need God\'s guidance.',
                'requester_name' => null,
                'requester_email' => null,
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'family',
                'prayer_count' => 8,
                'is_urgent' => false,
                'is_anonymous' => true,
            ],
            [
                'title' => 'Job Search',
                'request' => 'Please pray for me as I search for meaningful employment. May God open the right doors and guide me to where I can serve Him best.',
                'requester_name' => 'Michael Johnson',
                'requester_email' => 'michael.j@email.com',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'work',
                'prayer_count' => 15,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Spiritual Growth',
                'request' => 'Pray for my spiritual journey and growth in faith. I want to deepen my relationship with God and live according to His will.',
                'requester_name' => null,
                'requester_email' => null,
                'visibility' => 'anonymous',
                'status' => 'active',
                'category' => 'spiritual',
                'prayer_count' => 23,
                'is_urgent' => false,
                'is_anonymous' => true,
            ],
            [
                'title' => 'Travel Safety',
                'request' => 'Please pray for safe travels for our church mission team as we journey to serve in the community next week.',
                'requester_name' => 'Father Dimitri',
                'requester_email' => 'fr.dimitri@church.org',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'travel',
                'prayer_count' => 31,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Emergency Surgery',
                'request' => 'Urgent prayers needed for my son who is undergoing emergency surgery. Please pray for the doctors and for his recovery.',
                'requester_name' => 'Sarah Williams',
                'requester_email' => 'sarah.w@email.com',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'health',
                'prayer_count' => 47,
                'is_urgent' => true,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Answered Prayer',
                'request' => 'Thank you for your prayers! My mother\'s test results came back clear. God is good!',
                'requester_name' => 'Elena Rodriguez',
                'requester_email' => 'elena.r@email.com',
                'visibility' => 'public',
                'status' => 'answered',
                'category' => 'health',
                'prayer_count' => 35,
                'is_urgent' => false,
                'is_anonymous' => false,
                'answered_at' => now()->subDays(3),
                'answer_notes' => 'Medical tests came back clear, full recovery confirmed.',
            ],
            [
                'title' => 'Marriage Guidance',
                'request' => 'Pray for wisdom and guidance in my marriage. We are facing challenges and need God\'s help to strengthen our bond.',
                'requester_name' => null,
                'requester_email' => null,
                'visibility' => 'private',
                'status' => 'active',
                'category' => 'family',
                'prayer_count' => 5,
                'is_urgent' => false,
                'is_anonymous' => true,
            ],
            [
                'title' => 'Church Building Fund',
                'request' => 'Pray for our church building fund campaign. May God bless our efforts to expand our facilities to serve more people.',
                'requester_name' => 'Parish Council',
                'requester_email' => 'council@church.org',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'spiritual',
                'prayer_count' => 67,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Student Exams',
                'request' => 'Pray for all our students taking final exams this week. May they find peace and clarity in their studies.',
                'requester_name' => 'Youth Group',
                'requester_email' => 'youth@church.org',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'other',
                'prayer_count' => 19,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Missionary Family',
                'request' => 'Pray for the Petrović family serving as missionaries in Serbia. May God protect them and bless their ministry.',
                'requester_name' => 'Mission Committee',
                'requester_email' => 'missions@church.org',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'spiritual',
                'prayer_count' => 41,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Community Outreach',
                'request' => 'Pray for our upcoming community outreach event. May God use us to serve and bless our neighbors.',
                'requester_name' => 'Outreach Team',
                'requester_email' => 'outreach@church.org',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'spiritual',
                'prayer_count' => 28,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Peace in the World',
                'request' => 'Pray for peace in our world, especially in areas of conflict. May God\'s love and mercy prevail.',
                'requester_name' => null,
                'requester_email' => null,
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'spiritual',
                'prayer_count' => 156,
                'is_urgent' => false,
                'is_anonymous' => true,
            ],
            [
                'title' => 'New Baby',
                'request' => 'Pray for the safe arrival of our new baby due next month. May God bless our growing family.',
                'requester_name' => 'The Johnson Family',
                'requester_email' => 'johnson.family@email.com',
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'family',
                'prayer_count' => 73,
                'is_urgent' => false,
                'is_anonymous' => false,
            ],
            [
                'title' => 'Elderly Care',
                'request' => 'Pray for wisdom in caring for my aging parents. May God give me strength and patience.',
                'requester_name' => null,
                'requester_email' => null,
                'visibility' => 'public',
                'status' => 'active',
                'category' => 'family',
                'prayer_count' => 34,
                'is_urgent' => false,
                'is_anonymous' => true,
            ],
        ];

        foreach ($prayerRequests as $request) {
            PrayerRequest::create($request);
        }
    }
}