import React, { createContext, useContext, useState, useEffect } from 'react'

// Translation data
const translations = {
  en: {
    // Header
    churchName: 'Holy Orthodox Church',
    churchTagline: '✠ In Christ we trust ✠',
    welcome: 'Welcome',
    login: 'Login',
    signUp: 'Sign Up',
    dashboard: 'Dashboard',
    
    // Navigation
    home: 'Home',
    about: 'About',
    calendar: 'Calendar',
    news: 'News & Announcements',
    bulletin: 'Bulletin Board',
    search: 'Search',
    contact: 'Contact',
    
    // Home page
    welcomeTitle: 'Welcome to Our Orthodox Community',
    welcomeText: 'Join us in worship, fellowship, and spiritual growth. Discover the beauty of Orthodox Christianity and become part of our loving community. Experience the ancient traditions and timeless wisdom of the Orthodox faith.',
    dailyInspiration: 'Daily Inspiration',
    
    // Features
    spiritualLearning: 'Spiritual Learning',
    spiritualLearningText: 'Discover the rich traditions and teachings of Orthodox Christianity through our educational programs and spiritual guidance.',
    communityFellowship: 'Community Fellowship',
    communityFellowshipText: 'Join our warm and welcoming community where faith, friendship, and fellowship come together in Christ\'s love.',
    sacredWorship: 'Sacred Worship',
    sacredWorshipText: 'Experience the beauty and majesty of Orthodox worship through our Divine Liturgy and sacred services.',
    
    // Service Times
    serviceTimesTitle: 'Worship Service Times',
    serviceTimesText: 'Join us for our weekly services and special celebrations',
    sunday: 'Sunday',
    wednesday: 'Wednesday',
    saturday: 'Saturday',
    feastDays: 'Feast Days',
    divineLiturgy: 'Divine Liturgy',
    vespers: 'Vespers',
    greatVespers: 'Great Vespers',
    specialServices: 'Special Services',
    matinsTime: 'Matins at 8:00 AM',
    eveningPrayer: 'Evening Prayer',
    eveningWorship: 'Evening Worship',
    checkCalendar: 'Check Calendar',
    varies: 'Varies',
    
    // Events
    upcomingEvents: 'Upcoming Events',
    stayConnected: 'Stay connected with our community activities',
    viewCalendar: 'View Calendar',
    calendarSubtitle: 'Upcoming church events and liturgies',
    blogSubtitle: 'Latest news, reflections, and teachings from our church community',
    bulletinSubtitle: 'Stay updated with announcements and community notices',
    
    // Blog/Post page
    backToBlog: 'Back to Blog',
    views: 'views',
    minRead: 'min read',
    publishedOn: 'Published on',
    lastUpdated: 'Last updated',
    
    // Dashboard menu
    administration: 'Administration',
    userManagement: 'User Management',
    eventsCalendar: 'Events & Calendar',
    blogNews: 'Blog & News',
    bulletinBoard: 'Bulletin Board',
    dailyQuotes: 'Daily Quotes',
    contentModeration: 'Content Moderation',
    myAccount: 'My Account',
    accountSettings: 'Account Settings',
    
    // Prayer Requests translations
    prayerRequestsDescription: 'Share your prayer requests with our community and join us in prayer for others.',
    submitPrayerRequest: 'Submit Prayer Request',
    submitPrayerRequestDescription: 'Share your prayer needs with our church community. Your request will be lifted up in prayer.',
    prayerRequest: 'Prayer Request',
    filterByCategory: 'Filter by Category',
    filterByStatus: 'Filter by Status',
    applyFilters: 'Apply Filters',
    peoplePrayed: 'People Prayed',
    prayForThis: 'Pray for This',
    viewDetails: 'View Details',
    noPrayerRequests: 'No Prayer Requests Found',
    noPrayerRequestsDescription: 'There are no prayer requests matching your current filters. Try adjusting your search criteria.',
    prayForRequest: 'Pray for This Request',
    prayerConfirmationMessage: 'Are you sure you want to pray for this request? Your prayer will be counted and the person will be blessed.',
    prayNow: 'Pray Now',
    cancel: 'Cancel',
    prayed: 'Prayed',
    prayerAnswered: 'Prayer Answered',
    answeredOn: 'Answered on',
    prayerTips: 'Prayer Tips',
    prayerTipsContent: 'Take a moment to pray sincerely for this request. Your prayers make a difference in people\'s lives.',
    submittedOn: 'Submitted on',
    backToPrayerRequests: 'Back to Prayer Requests',
    
    // Prayer Request Categories
    healthCategory: 'Health',
    familyCategory: 'Family',
    spiritualCategory: 'Spiritual',
    workCategory: 'Work',
    travelCategory: 'Travel',
    otherCategory: 'Other',
    allCategories: 'All Categories',
    
    // Prayer Request Status
    activeStatus: 'Active',
    answeredStatus: 'Answered',
    
    // Prayer Request Form
    prayerRequestTitle: 'Prayer Request Title',
    prayerRequestTitlePlaceholder: 'Brief title for your prayer request',
    prayerRequestContent: 'Prayer Request Details',
    prayerRequestContentPlaceholder: 'Please share the details of what you would like our community to pray for...',
    category: 'Category',
    selectCategory: 'Select a category',
    visibilitySettings: 'Visibility Settings',
    publicVisibility: 'Public',
    publicVisibilityDescription: 'Visible to everyone in the community',
    anonymousVisibility: 'Anonymous',
    anonymousVisibilityDescription: 'Visible to everyone but without your personal details',
    privateVisibility: 'Private',
    privateVisibilityDescription: 'Only visible to you and church administrators',
    personalInformation: 'Personal Information',
    optional: 'Optional',
    yourName: 'Your Name',
    yourNamePlaceholder: 'Enter your name (optional)',
    yourEmail: 'Your Email',
    yourEmailPlaceholder: 'Enter your email (optional)',
    additionalOptions: 'Additional Options',
    markAsUrgent: 'Mark as Urgent',
    markAsUrgentDescription: 'This request needs immediate prayer attention',
    hidePersonalDetails: 'Hide Personal Details',
    hidePersonalDetailsDescription: 'Show request publicly but keep your identity private',
    importantNote: 'Important Note',
    prayerRequestPrivacyNote: 'All prayer requests are reviewed before being published. Personal information is kept confidential and only shared with your permission.',
    urgent: 'Urgent',
    
    // Admin Prayer Requests
    managePrayerRequests: 'Manage Prayer Requests',
    addNewPrayerRequest: 'Add New Prayer Request',
    activeRequests: 'Active Requests',
    answeredRequests: 'Answered Requests',
    urgentRequests: 'Urgent Requests',
    allStatuses: 'All Statuses',
    allVisibilities: 'All Visibilities',
    filterByVisibility: 'Filter by Visibility',
    requester: 'Requester',
    prayers: 'Prayers',
    created: 'Created',
    actions: 'Actions',
    edit: 'Edit',
    markAsAnswered: 'Mark as Answered',
    delete: 'Delete',
    noPrayerRequestsFound: 'No Prayer Requests Found',
    noPrayerRequestsFoundDescription: 'There are no prayer requests matching your current filters.',
    confirmDelete: 'Confirm Delete',
    deletePrayerRequestConfirmation: 'Are you sure you want to delete this prayer request? This action cannot be undone.',
    answerPrayerRequestDescription: 'Mark this prayer request as answered and add notes about how the prayer was answered.',
    answerNotes: 'Answer Notes',
    answerNotesPlaceholder: 'Describe how this prayer was answered...',
    anonymous: 'Anonymous',
    archivedStatus: 'Archived',
    
    // Search page
    searchOurContent: 'Search Our Content',
    searchSubtitle: 'Find posts, events, bulletins, and more from our Orthodox community',
    searchPlaceholder: 'Search for posts, events, announcements...',
    advancedFilters: 'Advanced Filters',
    contentTypes: 'Content Types',
    selectContentTypes: 'Select content types to search',
    fromDate: 'From Date',
    startDate: 'Start date',
    toDate: 'To Date',
      endDate: 'End date',
      categoryPosts: 'Category (Posts)',
      eventType: 'Event Type',
    selectEventType: 'Select event type',
    priorityBulletins: 'Priority (Bulletins)',
    selectPriority: 'Select priority',
    clearFilters: 'Clear Filters',
    searchNow: 'Search Now',
    popularPosts: 'Popular Posts',
    latestBulletins: 'Latest Bulletins',
    searchTips: 'Search Tips',
    searchTip1: 'Use specific keywords for better results',
    searchTip2: 'Try searching in different languages',
    searchTip3: 'Use date filters to find content from specific periods',
    searchTip4: 'Select content types to narrow your search',
    
    // Quick Search Cards
    viewAllPosts: 'View All Posts',
    viewAllEvents: 'View All Events',
    viewAllBulletins: 'View All Bulletins',
    
    // Search Results
    foundResults: 'Found {count} results for "{query}"',
    noResultsFound: 'No results found',
    tryAdjustingSearch: 'Try adjusting your search criteria or search terms.',
    allResults: 'All',
    postsResults: 'Posts',
    eventsResults: 'Events',
      bulletinsResults: 'Bulletins',
      selectTypes: 'Select types',
    allTypes: 'All types',
    allPriorities: 'All priorities',
    
    // Content Types
    postsLabel: 'Posts',
    eventsLabel: 'Events',
    bulletinsLabel: 'Bulletins',
    
    // Categories
      newsCategory: 'News',
      announcementsCategory: 'Announcements',
      communityCategory: 'Community',
    
    // Event Types
    liturgyType: 'Liturgy',
    feastType: 'Feast Day',
    meetingType: 'Meeting',
    socialType: 'Social Event',
    
    // Priorities
    lowPriority: 'Low',
    normalPriority: 'Normal',
    highPriority: 'High',
    urgentPriority: 'Urgent',
    
    thisSunday: 'This Sunday',
    nextWeek: 'Next Week',
    comingSoon: 'Coming Soon',
    parishPotluck: 'Parish Potluck',
    afterLiturgy: 'After Divine Liturgy',
    fellowshipHall: 'Fellowship Hall',
    potluckText: 'Join us for a community meal and fellowship after the Sunday service. All are welcome!',
    bibleStudy: 'Bible Study',
    tuesdayEvening: 'Tuesday, 7:00 PM',
    allAgesWelcome: 'All ages welcome',
    bibleStudyText: 'Join us for weekly Bible study and discussion. Deepen your faith and understanding of Scripture.',
    youthRetreat: 'Youth Retreat',
    nextMonth: 'Next Month',
    mountainCenter: 'Mountain Retreat Center',
    youthRetreatText: 'A weekend retreat for young people to grow in faith and fellowship in God\'s beautiful creation.',
    
    // Call to Action
    joinCommunity: 'Join Our Community',
    joinText: 'Whether you\'re seeking spiritual growth, looking for a church home, or simply curious about Orthodox Christianity, we welcome you with open arms. Come experience the beauty of ancient worship and the warmth of Christian fellowship.',
    learnMore: 'Learn More',
    
    // Contact Info
    address: '123 Church Street, City, State',
    phone: '(555) 123-4567',
    email: 'info@holyorthodox.org',
    
    // Footer
    faithCommunity: 'A community of faith and fellowship',
    allRightsReserved: 'All rights reserved',
    
    // Languages
    language: 'Language',
    english: 'English',
    french: 'Français',
    serbian: 'Српски',
    
    // Authentication
    memberLogin: 'Member Login',
    memberRegister: 'Create Account',
    emailAddress: 'Email Address',
    emailPlaceholder: 'your@email.com',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    fullName: 'Full Name',
    fullNamePlaceholder: 'John Doe',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    backToLogin: 'Back to login',
    or: 'or',
    verifyEmail: 'Verify Your Email',
    verificationSent: 'A verification link has been sent to your email address.',
    checkEmail: 'Please check your email and click the verification link to verify your account.',
    resendVerification: 'Resend Verification Email',
    verificationEmailSent: 'Verification email sent!',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    resetLinkSent: 'Password reset link sent to your email!',
    
    // Contact Page
    contactUs: 'Contact Us',
    contactIntro: 'We\'d love to hear from you. Get in touch with us for any questions, prayer requests, or to learn more about our Orthodox community.',
    sendMessage: 'Send us a Message',
    namePlaceholder: 'Your full name',
    subject: 'Subject',
    subjectPlaceholder: 'What is this about?',
    message: 'Message',
    messagePlaceholder: 'Tell us how we can help...',
    sendMessageBtn: 'Send Message',
    visitUs: 'Visit Us',
    officeHours: 'Office Hours',
    mondayFriday: 'Monday - Friday',
    
    // About Page
    aboutUs: 'About Us',
    ourHistory: 'Our History',
    ourMission: 'Our Mission',
    ourValues: 'Our Values',
    clergy: 'Our Clergy',
    ministries: 'Ministries',
    historyText: 'Founded in faith and rooted in Orthodox tradition, our parish has been a beacon of hope and spiritual guidance in our community for over decades. We continue the ancient traditions of the Orthodox Church while serving the needs of our modern faithful.',
    missionText: 'Our mission is to glorify God through worship, fellowship, and service, following the teachings of Jesus Christ and the traditions of the Holy Orthodox Church. We strive to be a welcoming community for all who seek spiritual growth.',
    valuesText: 'We hold fast to the Orthodox faith, emphasizing prayer, fasting, almsgiving, and the sacramental life. Our community values include love, compassion, humility, and service to others.',
    orthodoxTradition: 'Orthodox Tradition',
    communityService: 'Community Service',
    spiritualGrowth: 'Spiritual Growth',
    traditionText: 'We maintain the ancient liturgical traditions and theological teachings passed down through centuries of Orthodox Christianity.',
    serviceText: 'Our church actively serves the local community through charitable works, food drives, and support for those in need.',
    growthText: 'We provide opportunities for spiritual education, Bible study, and personal growth in the Orthodox faith.',
    joinOurFamily: 'Join Our Church Family',
    
    // Dashboard
    memberDashboard: 'Member Dashboard',
    memberArea: 'Member Area',
    backToSite: 'Back to Site',
    logout: 'Logout',
    settings: 'Settings',
    profile: 'Profile',
    security: 'Security',
    appearance: 'Appearance',
    twoFactor: 'Two-Factor Auth',
    welcomeBack: 'Welcome back',
    dashboardIntro: 'Access your member resources and manage your account settings.',
    
    // Event Registration
    eventRegistration: 'Event Registration',
    registerForEvent: 'Register for Event',
    eventRegistrationDescription: 'Register for upcoming church events and activities.',
    registrationForm: 'Registration Form',
    registrantName: 'Full Name',
    registrantEmail: 'Email Address',
    totalAttendees: 'Number of Attendees',
    registrationNotes: 'Additional Notes',
    registrationNotesPlaceholder: 'Any dietary restrictions, accessibility needs, or other important information...',
    submitRegistration: 'Submit Registration',
    registrationSubmitted: 'Registration Submitted',
    registrationSuccess: 'Your registration has been submitted successfully!',
    registrationConfirmation: 'Registration Confirmation',
    registrationDetails: 'Registration Details',
    registrationStatus: 'Status',
    registrationDate: 'Registration Date',
    eventCapacity: 'Event Capacity',
    availableSpots: 'Available Spots',
    registrationRequired: 'Registration Required',
    registrationOpen: 'Registration Open',
    registrationClosed: 'Registration Closed',
    eventFull: 'Event Full',
    waitlistAvailable: 'Waitlist Available',
    registrationDeadline: 'Registration Deadline',
    registrationOpens: 'Registration Opens',
    pending: 'Pending',
    confirmed: 'Confirmed',
    waitlisted: 'Waitlisted',
    cancelled: 'Cancelled',
    checkedIn: 'Checked In',
    checkIn: 'Check In',
    cancelRegistration: 'Cancel Registration',
    editRegistration: 'Edit Registration',
    viewRegistration: 'View Registration',
    registrationHistory: 'Registration History',
    myRegistrations: 'My Registrations',
    manageRegistrations: 'Manage Registrations',
    allRegistrations: 'All Registrations',
    eventRegistrations: 'Event Registrations',
    registrationStats: 'Registration Statistics',
    totalRegistrations: 'Total Registrations',
    confirmedRegistrations: 'Confirmed Registrations',
    pendingRegistrations: 'Pending Registrations',
    waitlistRegistrations: 'Waitlist Registrations',
    checkedInCount: 'Checked In',
    registrationFees: 'Registration Fees',
    paymentRequired: 'Payment Required',
    paymentPending: 'Payment Pending',
    paymentCompleted: 'Payment Completed',
    paymentFailed: 'Payment Failed',
    noPaymentRequired: 'No Payment Required',
    registrationInstructions: 'Registration Instructions',
    registrationInstructionsPlaceholder: 'Please read the following instructions before registering...',
    dietaryRestrictions: 'Dietary Restrictions',
    accessibilityNeeds: 'Accessibility Needs',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone Number',
    agreeToTerms: 'I agree to the terms and conditions',
    termsAndConditions: 'Terms and Conditions',
    privacyPolicy: 'Privacy Policy',
    registrationPolicy: 'Registration Policy',
    refundPolicy: 'Refund Policy',
    contactOrganizer: 'Contact Event Organizer',
    eventOrganizer: 'Event Organizer',
    registrationContact: 'Registration Contact',
    registrationEmail: 'Registration Email',
    registrationPhone: 'Registration Phone',
    joinWaitlist: 'Join Waitlist',
    eventFullMessage: 'This event is at full capacity. You may join the waitlist if available.',
    registrationClosedMessage: 'Registration for this event is currently closed.',
    backToCalendar: 'Back to Calendar',
    confirmCancelRegistration: 'Are you sure you want to cancel your registration?',
    waitlistPosition: 'Waitlist Position',
    waitlistPositionMessage: 'You are #{position} on the waitlist.',
    checkedInAt: 'Checked in at {time}',
    paymentStatus: 'Payment Status',
    event: 'Event',
    searchRegistrations: 'Search registrations...',
    filterByEvent: 'Filter by Event',
    allEvents: 'All Events',
    noRegistrations: 'No registrations found',
    noRegistrationsMessage: 'No event registrations match your current filters.',
    moveToWaitlist: 'Move to Waitlist',
    confirm: 'Confirm',
    confirmDeleteRegistrationMessage: 'Are you sure you want to delete this registration? This action cannot be undone.',
    manageRegistrationsDescription: 'Manage and track event registrations, check-ins, and waitlist positions.'
  },
  
  fr: {
    // Header
    churchName: 'Sainte Église Orthodoxe',
    churchTagline: '✠ En Christ nous croyons ✠',
    welcome: 'Bienvenue',
    login: 'Connexion',
    signUp: 'S\'inscrire',
    dashboard: 'Tableau de bord',
    
    // Navigation
    home: 'Accueil',
    about: 'À propos',
    calendar: 'Calendrier',
    news: 'Nouvelles et annonces',
    bulletin: 'Tableau d\'affichage',
    prayerRequests: 'Demandes de prière',
    search: 'Recherche',
    contact: 'Contact',
    
    // Home page
    welcomeTitle: 'Bienvenue dans notre communauté orthodoxe',
    welcomeText: 'Rejoignez-nous dans le culte, la communion fraternelle et la croissance spirituelle. Découvrez la beauté du christianisme orthodoxe et devenez membre de notre communauté aimante. Expérimentez les traditions anciennes et la sagesse intemporelle de la foi orthodoxe.',
    dailyInspiration: 'Inspiration quotidienne',
    
    // Features
    spiritualLearning: 'Apprentissage spirituel',
    spiritualLearningText: 'Découvrez les riches traditions et enseignements du christianisme orthodoxe à travers nos programmes éducatifs et notre guidance spirituelle.',
    communityFellowship: 'Communion fraternelle',
    communityFellowshipText: 'Rejoignez notre communauté chaleureuse et accueillante où la foi, l\'amitié et la communion fraternelle se rassemblent dans l\'amour du Christ.',
    sacredWorship: 'Culte sacré',
    sacredWorshipText: 'Expérimentez la beauté et la majesté du culte orthodoxe à travers notre Divine Liturgie et nos services sacrés.',
    
    // Service Times
    serviceTimesTitle: 'Horaires des services religieux',
    serviceTimesText: 'Rejoignez-nous pour nos services hebdomadaires et célébrations spéciales',
    sunday: 'Dimanche',
    wednesday: 'Mercredi',
    saturday: 'Samedi',
    feastDays: 'Jours de fête',
    divineLiturgy: 'Divine Liturgie',
    vespers: 'Vêpres',
    greatVespers: 'Grandes Vêpres',
    specialServices: 'Services spéciaux',
    matinsTime: 'Matines à 8h00',
    eveningPrayer: 'Prière du soir',
    eveningWorship: 'Culte du soir',
    checkCalendar: 'Vérifier le calendrier',
    varies: 'Variable',
    
    // Events
    upcomingEvents: 'Événements à venir',
    stayConnected: 'Restez connecté avec nos activités communautaires',
    viewCalendar: 'Voir le calendrier',
    calendarSubtitle: 'Événements et liturgies à venir de l\'église',
    blogSubtitle: 'Dernières nouvelles, réflexions et enseignements de notre communauté paroissiale',
    bulletinSubtitle: 'Restez informé des annonces et avis de la communauté',
    
    // Blog/Post page
    backToBlog: 'Retour au blog',
    views: 'vues',
    minRead: 'min de lecture',
    publishedOn: 'Publié le',
    lastUpdated: 'Dernière mise à jour',
    
    // Dashboard menu
    administration: 'Administration',
    userManagement: 'Gestion des utilisateurs',
    eventsCalendar: 'Événements et calendrier',
    blogNews: 'Blog et actualités',
    bulletinBoard: 'Tableau d\'affichage',
    dailyQuotes: 'Citations quotidiennes',
    contentModeration: 'Modération de contenu',
    myAccount: 'Mon compte',
    accountSettings: 'Paramètres du compte',
    
    // Prayer Requests translations
    prayerRequestsDescription: 'Partagez vos demandes de prière avec notre communauté et joignez-vous à nous dans la prière pour les autres.',
    submitPrayerRequest: 'Soumettre une demande de prière',
    submitPrayerRequestDescription: 'Partagez vos besoins de prière avec notre communauté paroissiale. Votre demande sera portée dans la prière.',
    prayerRequest: 'Demande de prière',
    filterByCategory: 'Filtrer par catégorie',
    filterByStatus: 'Filtrer par statut',
    applyFilters: 'Appliquer les filtres',
    peoplePrayed: 'Personnes ont prié',
    prayForThis: 'Prier pour ceci',
    viewDetails: 'Voir les détails',
    noPrayerRequests: 'Aucune demande de prière trouvée',
    noPrayerRequestsDescription: 'Il n\'y a pas de demandes de prière correspondant à vos filtres actuels. Essayez d\'ajuster vos critères de recherche.',
    prayForRequest: 'Prier pour cette demande',
    prayerConfirmationMessage: 'Êtes-vous sûr de vouloir prier pour cette demande ? Votre prière sera comptée et la personne sera bénie.',
    prayNow: 'Prier maintenant',
    cancel: 'Annuler',
    prayed: 'Prié',
    prayerAnswered: 'Prière exaucée',
    answeredOn: 'Exaucée le',
    prayerTips: 'Conseils de prière',
    prayerTipsContent: 'Prenez un moment pour prier sincèrement pour cette demande. Vos prières font une différence dans la vie des gens.',
    submittedOn: 'Soumise le',
    backToPrayerRequests: 'Retour aux demandes de prière',
    
    // Prayer Request Categories
    healthCategory: 'Santé',
    familyCategory: 'Famille',
    spiritualCategory: 'Spirituel',
    workCategory: 'Travail',
    travelCategory: 'Voyage',
    otherCategory: 'Autre',
    allCategories: 'Toutes les catégories',
    
    // Prayer Request Status
    activeStatus: 'Actif',
    answeredStatus: 'Exaucé',
    
    // Prayer Request Form
    prayerRequestTitle: 'Titre de la demande de prière',
    prayerRequestTitlePlaceholder: 'Titre bref pour votre demande de prière',
    prayerRequestContent: 'Détails de la demande de prière',
    prayerRequestContentPlaceholder: 'Veuillez partager les détails de ce pour quoi vous souhaitez que notre communauté prie...',
    category: 'Catégorie',
    selectCategory: 'Sélectionner une catégorie',
    visibilitySettings: 'Paramètres de visibilité',
    publicVisibility: 'Public',
    publicVisibilityDescription: 'Visible par tout le monde dans la communauté',
    anonymousVisibility: 'Anonyme',
    anonymousVisibilityDescription: 'Visible par tout le monde mais sans vos détails personnels',
    privateVisibility: 'Privé',
    privateVisibilityDescription: 'Visible uniquement par vous et les administrateurs de l\'église',
    personalInformation: 'Informations personnelles',
    optional: 'Optionnel',
    yourName: 'Votre nom',
    yourNamePlaceholder: 'Entrez votre nom (optionnel)',
    yourEmail: 'Votre email',
    yourEmailPlaceholder: 'Entrez votre email (optionnel)',
    additionalOptions: 'Options supplémentaires',
    markAsUrgent: 'Marquer comme urgent',
    markAsUrgentDescription: 'Cette demande nécessite une attention de prière immédiate',
    hidePersonalDetails: 'Masquer les détails personnels',
    hidePersonalDetailsDescription: 'Afficher la demande publiquement mais garder votre identité privée',
    importantNote: 'Note importante',
    prayerRequestPrivacyNote: 'Toutes les demandes de prière sont examinées avant publication. Les informations personnelles sont confidentielles et ne sont partagées qu\'avec votre permission.',
    urgent: 'Urgent',
    
    // Search page
    searchOurContent: 'Rechercher dans notre contenu',
    searchSubtitle: 'Trouvez des articles, événements, bulletins et plus de notre communauté orthodoxe',
    searchPlaceholder: 'Rechercher des articles, événements, annonces...',
    advancedFilters: 'Filtres avancés',
    contentTypes: 'Types de contenu',
    selectContentTypes: 'Sélectionner les types de contenu à rechercher',
    fromDate: 'Date de début',
    startDate: 'Date de début',
    toDate: 'Date de fin',
      endDate: 'Date de fin',
      categoryPosts: 'Catégorie (Articles)',
      eventType: 'Type d\'événement',
    selectEventType: 'Sélectionner le type d\'événement',
    priorityBulletins: 'Priorité (Bulletins)',
    selectPriority: 'Sélectionner la priorité',
    clearFilters: 'Effacer les filtres',
    searchNow: 'Rechercher maintenant',
    popularPosts: 'Articles populaires',
    latestBulletins: 'Derniers bulletins',
    searchTips: 'Conseils de recherche',
    searchTip1: 'Utilisez des mots-clés spécifiques pour de meilleurs résultats',
    searchTip2: 'Essayez de rechercher dans différentes langues',
    searchTip3: 'Utilisez les filtres de date pour trouver du contenu de périodes spécifiques',
    searchTip4: 'Sélectionnez les types de contenu pour affiner votre recherche',
    
    // Quick Search Cards
    viewAllPosts: 'Voir tous les articles',
    viewAllEvents: 'Voir tous les événements',
    viewAllBulletins: 'Voir tous les bulletins',
    
    // Search Results
    foundResults: 'Trouvé {count} résultats pour "{query}"',
    noResultsFound: 'Aucun résultat trouvé',
    tryAdjustingSearch: 'Essayez d\'ajuster vos critères de recherche ou vos termes de recherche.',
    allResults: 'Tous',
    postsResults: 'Articles',
    eventsResults: 'Événements',
      bulletinsResults: 'Bulletins',
      selectTypes: 'Sélectionner les types',
    allTypes: 'Tous les types',
    allPriorities: 'Toutes les priorités',
    
    // Content Types
    postsLabel: 'Articles',
    eventsLabel: 'Événements',
    bulletinsLabel: 'Bulletins',
    
    // Categories
      newsCategory: 'Actualités',
      announcementsCategory: 'Annonces',
      communityCategory: 'Communauté',
    
    // Event Types
    liturgyType: 'Liturgie',
    feastType: 'Jour de fête',
    meetingType: 'Réunion',
    socialType: 'Événement social',
    
    // Priorities
    lowPriority: 'Faible',
    normalPriority: 'Normal',
    highPriority: 'Élevé',
    urgentPriority: 'Urgent',
    
    thisSunday: 'Ce dimanche',
    nextWeek: 'La semaine prochaine',
    comingSoon: 'Bientôt',
    parishPotluck: 'Repas communautaire',
    afterLiturgy: 'Après la Divine Liturgie',
    fellowshipHall: 'Salle de communion',
    potluckText: 'Rejoignez-nous pour un repas communautaire et une communion fraternelle après le service du dimanche. Tous sont les bienvenus!',
    bibleStudy: 'Étude biblique',
    tuesdayEvening: 'Mardi, 19h00',
    allAgesWelcome: 'Tous âges bienvenus',
    bibleStudyText: 'Rejoignez-nous pour l\'étude biblique hebdomadaire et la discussion. Approfondissez votre foi et votre compréhension des Écritures.',
    youthRetreat: 'Retraite des jeunes',
    nextMonth: 'Le mois prochain',
    mountainCenter: 'Centre de retraite en montagne',
    youthRetreatText: 'Une retraite de week-end pour les jeunes pour grandir dans la foi et la communion fraternelle dans la belle création de Dieu.',
    
    // Call to Action
    joinCommunity: 'Rejoignez notre communauté',
    joinText: 'Que vous cherchiez la croissance spirituelle, une église où vous sentir chez vous, ou que vous soyez simplement curieux du christianisme orthodoxe, nous vous accueillons à bras ouverts. Venez expérimenter la beauté du culte ancien et la chaleur de la communion chrétienne.',
    learnMore: 'En savoir plus',
    
    // Contact Info
    address: '123 Rue de l\'Église, Ville, État',
    phone: '(555) 123-4567',
    email: 'info@sainteorthodoxe.org',
    
    // Footer
    faithCommunity: 'Une communauté de foi et de communion fraternelle',
    allRightsReserved: 'Tous droits réservés',
    
    // Languages
    language: 'Langue',
    english: 'English',
    french: 'Français',
    serbian: 'Српски',
    
    // Authentication
    memberLogin: 'Connexion membre',
    memberRegister: 'Créer un compte',
    emailAddress: 'Adresse e-mail',
    emailPlaceholder: 'votre@email.com',
    password: 'Mot de passe',
    passwordPlaceholder: 'Entrez votre mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'Jean Dupont',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié?',
    dontHaveAccount: "Vous n'avez pas de compte?",
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    createAccount: 'Créer un compte',
    backToLogin: 'Retour à la connexion',
    or: 'ou',
    verifyEmail: 'Vérifiez votre e-mail',
    verificationSent: 'Un lien de vérification a été envoyé à votre adresse e-mail.',
    checkEmail: 'Veuillez vérifier votre e-mail et cliquer sur le lien de vérification pour vérifier votre compte.',
    resendVerification: 'Renvoyer l\'e-mail de vérification',
    verificationEmailSent: 'E-mail de vérification envoyé!',
    resetPassword: 'Réinitialiser le mot de passe',
    sendResetLink: 'Envoyer le lien de réinitialisation',
    resetLinkSent: 'Lien de réinitialisation du mot de passe envoyé à votre e-mail!',
    
    // Contact Page
    contactUs: 'Contactez-nous',
    contactIntro: 'Nous aimerions avoir de vos nouvelles. Contactez-nous pour toute question, demande de prière, ou pour en savoir plus sur notre communauté orthodoxe.',
    sendMessage: 'Envoyez-nous un message',
    namePlaceholder: 'Votre nom complet',
    subject: 'Sujet',
    subjectPlaceholder: 'De quoi s\'agit-il?',
    message: 'Message',
    messagePlaceholder: 'Dites-nous comment nous pouvons vous aider...',
    sendMessageBtn: 'Envoyer le message',
    visitUs: 'Visitez-nous',
    officeHours: 'Heures de bureau',
    mondayFriday: 'Lundi - Vendredi',
    
    // About Page
    aboutUs: 'À propos de nous',
    ourHistory: 'Notre histoire',
    ourMission: 'Notre mission',
    ourValues: 'Nos valeurs',
    clergy: 'Notre clergé',
    ministries: 'Ministères',
    historyText: 'Fondée dans la foi et enracinée dans la tradition orthodoxe, notre paroisse est un phare d\'espoir et de guidance spirituelle dans notre communauté depuis des décennies. Nous perpétuons les traditions anciennes de l\'Église orthodoxe tout en servant les besoins de nos fidèles modernes.',
    missionText: 'Notre mission est de glorifier Dieu par le culte, la communion fraternelle et le service, en suivant les enseignements de Jésus-Christ et les traditions de la Sainte Église orthodoxe. Nous nous efforçons d\'être une communauté accueillante pour tous ceux qui cherchent la croissance spirituelle.',
    valuesText: 'Nous restons fidèles à la foi orthodoxe, en mettant l\'accent sur la prière, le jeûne, l\'aumône et la vie sacramentelle. Les valeurs de notre communauté incluent l\'amour, la compassion, l\'humilité et le service aux autres.',
    orthodoxTradition: 'Tradition orthodoxe',
    communityService: 'Service communautaire',
    spiritualGrowth: 'Croissance spirituelle',
    traditionText: 'Nous maintenons les traditions liturgiques anciennes et les enseignements théologiques transmis à travers des siècles de christianisme orthodoxe.',
    serviceText: 'Notre église sert activement la communauté locale par des œuvres caritatives, des collectes de nourriture et un soutien à ceux dans le besoin.',
    growthText: 'Nous offrons des opportunités d\'éducation spirituelle, d\'étude biblique et de croissance personnelle dans la foi orthodoxe.',
    joinOurFamily: 'Rejoignez notre famille d\'église',
    
    // Dashboard
    memberDashboard: 'Tableau de bord membre',
    memberArea: 'Espace membre',
    backToSite: 'Retour au site',
    logout: 'Déconnexion',
    settings: 'Paramètres',
    profile: 'Profil',
    security: 'Sécurité',
    appearance: 'Apparence',
    twoFactor: 'Authentification à deux facteurs',
    welcomeBack: 'Bon retour',
    dashboardIntro: 'Accédez à vos ressources de membre et gérez les paramètres de votre compte.',
    
    // Event Registration
    eventRegistration: 'Inscription aux événements',
    registerForEvent: 'S\'inscrire à l\'événement',
    eventRegistrationDescription: 'Inscrivez-vous aux événements et activités à venir de l\'église.',
    registrationForm: 'Formulaire d\'inscription',
    registrantName: 'Nom complet',
    registrantEmail: 'Adresse e-mail',
    totalAttendees: 'Nombre de participants',
    registrationNotes: 'Notes supplémentaires',
    registrationNotesPlaceholder: 'Toute restriction alimentaire, besoin d\'accessibilité ou autre information importante...',
    submitRegistration: 'Soumettre l\'inscription',
    registrationSubmitted: 'Inscription soumise',
    registrationSuccess: 'Votre inscription a été soumise avec succès !',
    registrationConfirmation: 'Confirmation d\'inscription',
    registrationDetails: 'Détails de l\'inscription',
    registrationStatus: 'Statut',
    registrationDate: 'Date d\'inscription',
    eventCapacity: 'Capacité de l\'événement',
    availableSpots: 'Places disponibles',
    registrationRequired: 'Inscription requise',
    registrationOpen: 'Inscription ouverte',
    registrationClosed: 'Inscription fermée',
    eventFull: 'Événement complet',
    waitlistAvailable: 'Liste d\'attente disponible',
    registrationDeadline: 'Date limite d\'inscription',
    registrationOpens: 'Inscription ouvre',
    pending: 'En attente',
    confirmed: 'Confirmé',
    waitlisted: 'Sur liste d\'attente',
    cancelled: 'Annulé',
    checkedIn: 'Enregistré',
    checkIn: 'Enregistrement',
    cancelRegistration: 'Annuler l\'inscription',
    editRegistration: 'Modifier l\'inscription',
    viewRegistration: 'Voir l\'inscription',
    registrationHistory: 'Historique des inscriptions',
    myRegistrations: 'Mes inscriptions',
    manageRegistrations: 'Gérer les inscriptions',
    allRegistrations: 'Toutes les inscriptions',
    eventRegistrations: 'Inscriptions aux événements',
    registrationStats: 'Statistiques d\'inscription',
    totalRegistrations: 'Total des inscriptions',
    confirmedRegistrations: 'Inscriptions confirmées',
    pendingRegistrations: 'Inscriptions en attente',
    waitlistRegistrations: 'Inscriptions sur liste d\'attente',
    checkedInCount: 'Enregistrés',
    registrationFees: 'Frais d\'inscription',
    paymentRequired: 'Paiement requis',
    paymentPending: 'Paiement en attente',
    paymentCompleted: 'Paiement terminé',
    paymentFailed: 'Paiement échoué',
    noPaymentRequired: 'Aucun paiement requis',
    registrationInstructions: 'Instructions d\'inscription',
    registrationInstructionsPlaceholder: 'Veuillez lire les instructions suivantes avant de vous inscrire...',
    dietaryRestrictions: 'Restrictions alimentaires',
    accessibilityNeeds: 'Besoins d\'accessibilité',
    emergencyContact: 'Contact d\'urgence',
    emergencyPhone: 'Numéro de téléphone d\'urgence',
    agreeToTerms: 'J\'accepte les termes et conditions',
    termsAndConditions: 'Termes et conditions',
    privacyPolicy: 'Politique de confidentialité',
    registrationPolicy: 'Politique d\'inscription',
    refundPolicy: 'Politique de remboursement',
    contactOrganizer: 'Contacter l\'organisateur',
    eventOrganizer: 'Organisateur de l\'événement',
    registrationContact: 'Contact d\'inscription',
    registrationEmail: 'E-mail d\'inscription',
    registrationPhone: 'Téléphone d\'inscription',
    joinWaitlist: 'Rejoindre la liste d\'attente',
    eventFullMessage: 'Cet événement est au complet. Vous pouvez rejoindre la liste d\'attente si disponible.',
    registrationClosedMessage: 'L\'inscription à cet événement est actuellement fermée.',
    backToCalendar: 'Retour au calendrier',
    confirmCancelRegistration: 'Êtes-vous sûr de vouloir annuler votre inscription ?',
    waitlistPosition: 'Position sur la liste d\'attente',
    waitlistPositionMessage: 'Vous êtes #{position} sur la liste d\'attente.',
    checkedInAt: 'Enregistré à {time}',
    paymentStatus: 'Statut du paiement',
    event: 'Événement',
    searchRegistrations: 'Rechercher des inscriptions...',
    filterByEvent: 'Filtrer par événement',
    allEvents: 'Tous les événements',
    allStatuses: 'Tous les statuts',
    noRegistrations: 'Aucune inscription trouvée',
    noRegistrationsMessage: 'Aucune inscription d\'événement ne correspond à vos filtres actuels.',
    moveToWaitlist: 'Déplacer vers la liste d\'attente',
    confirm: 'Confirmer',
    confirmDeleteRegistrationMessage: 'Êtes-vous sûr de vouloir supprimer cette inscription ? Cette action ne peut pas être annulée.',
    manageRegistrationsDescription: 'Gérez et suivez les inscriptions aux événements, les enregistrements et les positions sur la liste d\'attente.'
  },
  
  sr: {
    // Header
    churchName: 'Света Православна Црква',
    churchTagline: '✠ У Христу је наша вера ✠',
    welcome: 'Добродошли',
    login: 'Пријава',
    signUp: 'Регистрација',
    dashboard: 'Контролна табла',
    
    // Navigation
    home: 'Почетна',
    about: 'О нама',
    calendar: 'Календар',
    news: 'Вести и објаве',
    bulletin: 'Огласна табла',
    prayerRequests: 'Молитвени захтеви',
    search: 'Претрага',
    contact: 'Контакт',
    
    // Home page
    welcomeTitle: 'Добродошли у нашу православну заједницу',
    welcomeText: 'Придружите нам се у богослужењу, заједништву и духовном расту. Откријте лепоту православног хришћанства и постаните део наше љубљене заједнице. Доживите древне традиције и вечну мудрост православне вере.',
    dailyInspiration: 'Дневно надахнуће',
    
    // Features
    spiritualLearning: 'Духовно учење',
    spiritualLearningText: 'Откријте богате традиције и учења православног хришћанства кроз наше образовне програме и духовно вођење.',
    communityFellowship: 'Заједничко братство',
    communityFellowshipText: 'Придружите се нашој топлој и гостољубивој заједници где се вера, пријатељство и братство сусрећу у Христовој љубави.',
    sacredWorship: 'Света литургија',
    sacredWorshipText: 'Доживите лепоту и величанственост православног богослужења кроз нашу Божанствену Литургију и свете службе.',
    
    // Service Times
    serviceTimesTitle: 'Време богослужења',
    serviceTimesText: 'Придружите нам се на недељним службама и посебним прославама',
    sunday: 'Недеља',
    wednesday: 'Среда',
    saturday: 'Субота',
    feastDays: 'Празници',
    divineLiturgy: 'Божанствена Литургија',
    vespers: 'Вечерња',
    greatVespers: 'Велика Вечерња',
    specialServices: 'Посебне службе',
    matinsTime: 'Јутрење у 8:00',
    eveningPrayer: 'Вечерња молитва',
    eveningWorship: 'Вечерње богослужење',
    checkCalendar: 'Проверити календар',
    varies: 'Различито',
    
    // Events
    upcomingEvents: 'Предстојећи догађаји',
    stayConnected: 'Останите повезани са активностима наше заједнице',
    viewCalendar: 'Погледај календар',
    calendarSubtitle: 'Предстојећи догађаји и литургије цркве',
    blogSubtitle: 'Најновије вести, размишљања и учења из наше црквене заједнице',
    bulletinSubtitle: 'Будите у току са објавама и обавештењима заједнице',
    
    // Blog/Post page
    backToBlog: 'Назад на блог',
    views: 'прегледа',
    minRead: 'мин читања',
    publishedOn: 'Објављено',
    lastUpdated: 'Последње ажурирано',
    
    // Dashboard menu
    administration: 'Администрација',
    userManagement: 'Управљање корисницима',
    eventsCalendar: 'Догађаји и календар',
    blogNews: 'Блог и вести',
    bulletinBoard: 'Табла за објаве',
    dailyQuotes: 'Дневне цитате',
    contentModeration: 'Модерација садржаја',
    myAccount: 'Мој налог',
    accountSettings: 'Подешавања налога',
    
    // Prayer Requests translations
    prayerRequestsDescription: 'Поделите своје молитвене захтеве са нашом заједницом и придружите нам се у молитви за друге.',
    submitPrayerRequest: 'Пошаљи молитвени захтев',
    submitPrayerRequestDescription: 'Поделите своје молитвене потребе са нашом црквеном заједницом. Ваш захтев ће бити уздигнут у молитви.',
    prayerRequest: 'Молитвени захтев',
    filterByCategory: 'Филтрирај по категорији',
    filterByStatus: 'Филтрирај по статусу',
    applyFilters: 'Примени филтере',
    peoplePrayed: 'Људи су се молили',
    prayForThis: 'Моли се за ово',
    viewDetails: 'Погледај детаље',
    noPrayerRequests: 'Нису пронађени молитвени захтеви',
    noPrayerRequestsDescription: 'Нема молитвених захтева који одговарају вашим тренутним филтерима. Покушајте да прилагодите критеријуме претраге.',
    prayForRequest: 'Моли се за овај захтев',
    prayerConfirmationMessage: 'Да ли сте сигурни да желите да се молите за овај захтев? Ваша молитва ће бити забележена и особа ће бити благословена.',
    prayNow: 'Моли се сада',
    cancel: 'Откажи',
    prayed: 'Молио се',
    prayerAnswered: 'Молитва је услишена',
    answeredOn: 'Услишена',
    prayerTips: 'Савети за молитву',
    prayerTipsContent: 'Узмите тренутак да се искрено помолите за овај захтев. Ваше молитве праве разлику у животима људи.',
    submittedOn: 'Послато',
    backToPrayerRequests: 'Назад на молитвене захтеве',
    
    // Prayer Request Categories
    healthCategory: 'Здравље',
    familyCategory: 'Породица',
    spiritualCategory: 'Духовно',
    workCategory: 'Посао',
    travelCategory: 'Путовање',
    otherCategory: 'Остало',
    allCategories: 'Све категорије',
    
    // Prayer Request Status
    activeStatus: 'Активно',
    answeredStatus: 'Услишано',
    
    // Prayer Request Form
    prayerRequestTitle: 'Наслов молитвеног захтева',
    prayerRequestTitlePlaceholder: 'Кратак наслов за ваш молитвени захтев',
    prayerRequestContent: 'Детаљи молитвеног захтева',
    prayerRequestContentPlaceholder: 'Молимо поделите детаље за шта бисте желели да се наша заједница моли...',
    category: 'Категорија',
    selectCategory: 'Изаберите категорију',
    visibilitySettings: 'Подешавања видљивости',
    publicVisibility: 'Јавно',
    publicVisibilityDescription: 'Видљиво свима у заједници',
    anonymousVisibility: 'Анонимно',
    anonymousVisibilityDescription: 'Видљиво свима али без ваших личних детаља',
    privateVisibility: 'Приватно',
    privateVisibilityDescription: 'Видљиво само вама и администраторима цркве',
    personalInformation: 'Личне информације',
    optional: 'Опционо',
    yourName: 'Ваше име',
    yourNamePlaceholder: 'Унесите ваше име (опционо)',
    yourEmail: 'Ваш имејл',
    yourEmailPlaceholder: 'Унесите ваш имејл (опционо)',
    additionalOptions: 'Додатне опције',
    markAsUrgent: 'Означи као хитно',
    markAsUrgentDescription: 'Овај захтев захтева тренутну пажњу у молитви',
    hidePersonalDetails: 'Сакриј личне детаље',
    hidePersonalDetailsDescription: 'Прикажи захтев јавно али задржи свој идентитет приватним',
    importantNote: 'Важна напомена',
    prayerRequestPrivacyNote: 'Сви молитвени захтеви се прегледају пре објављивања. Личне информације се чувају поверљиво и деле се само са вашим одобрењем.',
    urgent: 'Хитно',
    
    // Search page
    searchOurContent: 'Претражите наш садржај',
    searchSubtitle: 'Пронађите чланке, догађаје, билтене и више из наше православне заједнице',
    searchPlaceholder: 'Претражите чланке, догађаје, објаве...',
    advancedFilters: 'Напредни филтери',
    contentTypes: 'Типови садржаја',
    selectContentTypes: 'Изаберите типове садржаја за претрагу',
    fromDate: 'Датум од',
    startDate: 'Датум почетка',
    toDate: 'Датум до',
      endDate: 'Датум завршетка',
      categoryPosts: 'Категорија (Чланци)',
      eventType: 'Тип догађаја',
    selectEventType: 'Изаберите тип догађаја',
    priorityBulletins: 'Приоритет (Билтени)',
    selectPriority: 'Изаберите приоритет',
    clearFilters: 'Обриши филтере',
    searchNow: 'Претражи сада',
    popularPosts: 'Популарни чланци',
    latestBulletins: 'Најновији билтени',
    searchTips: 'Савети за претрагу',
    searchTip1: 'Користите специфичне кључне речи за боље резултате',
    searchTip2: 'Покушајте да претражујете на различитим језицима',
    searchTip3: 'Користите филтере датума да пронађете садржај из одређених периода',
    searchTip4: 'Изаберите типове садржаја да сузите претрагу',
    
    // Quick Search Cards
    viewAllPosts: 'Погледај све чланке',
    viewAllEvents: 'Погледај све догађаје',
    viewAllBulletins: 'Погледај све билтене',
    
    // Search Results
    foundResults: 'Пронађено {count} резултата за "{query}"',
    noResultsFound: 'Нема резултата',
    tryAdjustingSearch: 'Покушајте да прилагодите критеријуме претраге или појмове за претрагу.',
    allResults: 'Све',
    postsResults: 'Чланци',
    eventsResults: 'Догађаји',
      bulletinsResults: 'Билтени',
      selectTypes: 'Изаберите типове',
    allTypes: 'Сви типови',
    allPriorities: 'Сви приоритети',
    
    // Content Types
    postsLabel: 'Чланци',
    eventsLabel: 'Догађаји',
    bulletinsLabel: 'Билтени',
    
    // Categories
      newsCategory: 'Вести',
      announcementsCategory: 'Објаве',
      communityCategory: 'Заједница',
    
    // Event Types
    liturgyType: 'Литургија',
    feastType: 'Празник',
    meetingType: 'Састанак',
    socialType: 'Друштвени догађај',
    
    // Priorities
    lowPriority: 'Низак',
    normalPriority: 'Нормалан',
    highPriority: 'Висок',
    urgentPriority: 'Хитан',
    
    thisSunday: 'Ове недеље',
    nextWeek: 'Следеће недеље',
    comingSoon: 'Ускоро',
    parishPotluck: 'Парохијски ручак',
    afterLiturgy: 'После Божанствене Литургије',
    fellowshipHall: 'Сала за заједништво',
    potluckText: 'Придружите нам се за заједнички оброк и братство после недељне службе. Сви су добродошли!',
    bibleStudy: 'Проучавање Библије',
    tuesdayEvening: 'Уторак, 19:00',
    allAgesWelcome: 'Сви узрасти добродошли',
    bibleStudyText: 'Придружите нам се за недељно проучавање Библије и расправу. Продубите своју веру и разумевање Светог Писма.',
    youthRetreat: 'Омладински повлачење',
    nextMonth: 'Следећи месец',
    mountainCenter: 'Планински центар за повлачење',
    youthRetreatText: 'Викенд повлачење за младе људе да расту у вери и заједништву у Божијој прелепој природи.',
    
    // Call to Action
    joinCommunity: 'Придружите се нашој заједници',
    joinText: 'Било да тражите духовни раст, тражите црквени дом, или сте једноставно радознали о православном хришћанству, дочекујемо вас отвореним срцем. Дођите и доживите лепоту древног богослужења и топлину хришћанског братства.',
    learnMore: 'Сазнајте више',
    
    // Contact Info
    address: 'Црквена 123, Град, Држава',
    phone: '(555) 123-4567',
    email: 'info@svetapravoslavna.org',
    
    // Footer
    faithCommunity: 'Заједница вере и братства',
    allRightsReserved: 'Сва права задржана',
    
    // Languages
    language: 'Језик',
    english: 'English',
    french: 'Français',
    serbian: 'Српски',
    
    // Authentication
    memberLogin: 'Пријава члана',
    memberRegister: 'Направите налог',
    emailAddress: 'Е-маил адреса',
    emailPlaceholder: 'vas@email.com',
    password: 'Лозинка',
    passwordPlaceholder: 'Унесите лозинку',
    confirmPassword: 'Потврдите лозинку',
    confirmPasswordPlaceholder: 'Потврдите лозинку',
    fullName: 'Пуно име',
    fullNamePlaceholder: 'Петар Петровић',
    rememberMe: 'Запамти ме',
    forgotPassword: 'Заборавили сте лозинку?',
    dontHaveAccount: 'Немате налог?',
    alreadyHaveAccount: 'Већ имате налог?',
    createAccount: 'Направите налог',
    backToLogin: 'Назад на пријаву',
    or: 'или',
    verifyEmail: 'Верификујте е-маил',
    verificationSent: 'Линк за верификацију је послат на вашу е-маил адресу.',
    checkEmail: 'Молимо проверите свој е-маил и кликните на линк за верификацију да бисте верификовали свој налог.',
    resendVerification: 'Поново пошаљи е-маил за верификацију',
    verificationEmailSent: 'Е-маил за верификацију послат!',
    resetPassword: 'Ресетујте лозинку',
    sendResetLink: 'Пошаљи линк за ресетовање',
    resetLinkSent: 'Линк за ресетовање лозинке послат на ваш е-маил!',
    
    // Contact Page
    contactUs: 'Контактирајте нас',
    contactIntro: 'Волели бисмо да чујемо од вас. Контактирајте нас за било која питања, молитвене захтеве, или да сазнате више о нашој православној заједници.',
    sendMessage: 'Пошаљите нам поруку',
    namePlaceholder: 'Ваше пуно име',
      subject: 'Предмет',
    subjectPlaceholder: 'О чему се ради?',
    message: 'Порука',
    messagePlaceholder: 'Реците нам како можемо да помогнемо...',
    sendMessageBtn: 'Пошаљи поруку',
    visitUs: 'Посетите нас',
    officeHours: 'Радно време канцеларије',
    mondayFriday: 'Понедељак - Петак',
    
    // About Page
    aboutUs: 'О нама',
    ourHistory: 'Наша историја',
    ourMission: 'Наша мисија',
    ourValues: 'Наше вредности',
    clergy: 'Наше свештенство',
    ministries: 'Служења',
    historyText: 'Основана у вери и укорењена у православној традицији, наша парохија је светионик наде и духовног вођења у нашој заједници већ деценијама. Настављамо древне традиције Православне цркве док служимо потребама наших савремених верника.',
    missionText: 'Наша мисија је да прославимо Бога кроз богослужење, заједништво и службу, следећи учења Исуса Христа и традиције Свете православне цркве. Настојимо да будемо гостољубива заједница за све који траже духовни раст.',
    valuesText: 'Држимо се православне вере, наглашавајући молитву, пост, милостињу и таинствени живот. Вредности наше заједнице укључују љубав, саосећање, смерност и службу другима.',
    orthodoxTradition: 'Православна традиција',
    communityService: 'Служење заједници',
    spiritualGrowth: 'Духовни раст',
    traditionText: 'Одржавамо древне литургијске традиције и теолошка учења преношена кроз векове православног хришћанства.',
    serviceText: 'Наша црква активно служи локалној заједници кроз добротворне радове, акције прикупљања хране и подршку онима којима је потребна помоћ.',
    growthText: 'Пружамо могућности за духовно образовање, проучавање Библије и лични раст у православној вери.',
    joinOurFamily: 'Придружите се нашој црквеној породици',
    
    // Dashboard
    memberDashboard: 'Контролна табла члана',
    memberArea: 'Чланска област',
    backToSite: 'Назад на сајт',
    logout: 'Одјава',
    settings: 'Подешавања',
    profile: 'Профил',
    security: 'Безбедност',
    appearance: 'Изглед',
    twoFactor: 'Двофакторска аутентификација',
    welcomeBack: 'Добро дошли назад',
    dashboardIntro: 'Приступите својим чланским ресурсима и управљајте подешавањима свог налога.',
    
    // Event Registration
    eventRegistration: 'Пријава за догађаје',
    registerForEvent: 'Пријави се за догађај',
    eventRegistrationDescription: 'Пријавите се за предстојеће црквене догађаје и активности.',
    registrationForm: 'Формулар за пријаву',
    registrantName: 'Пуно име',
    registrantEmail: 'Е-маил адреса',
    totalAttendees: 'Број учесника',
    registrationNotes: 'Додатне напомене',
    registrationNotesPlaceholder: 'Било какве дијететске рестрикције, потребе за приступачношћу или друге важне информације...',
    submitRegistration: 'Пошаљи пријаву',
    registrationSubmitted: 'Пријава послата',
    registrationSuccess: 'Ваша пријава је успешно послата!',
    registrationConfirmation: 'Потврда пријаве',
    registrationDetails: 'Детаљи пријаве',
    registrationStatus: 'Статус',
    registrationDate: 'Датум пријаве',
    eventCapacity: 'Капацитет догађаја',
    availableSpots: 'Доступна места',
    registrationRequired: 'Пријава потребна',
    registrationOpen: 'Пријава отворена',
    registrationClosed: 'Пријава затворена',
    eventFull: 'Догађај пун',
    waitlistAvailable: 'Листа чекања доступна',
    registrationDeadline: 'Рок за пријаву',
    registrationOpens: 'Пријава се отвара',
    pending: 'На чекању',
    confirmed: 'Потврђено',
    waitlisted: 'На листи чекања',
    cancelled: 'Отказано',
    checkedIn: 'Пријављено',
    checkIn: 'Пријава',
    cancelRegistration: 'Откажи пријаву',
    editRegistration: 'Уреди пријаву',
    viewRegistration: 'Погледај пријаву',
    registrationHistory: 'Историја пријава',
    myRegistrations: 'Моје пријаве',
    manageRegistrations: 'Управљај пријавама',
    allRegistrations: 'Све пријаве',
    eventRegistrations: 'Пријаве за догађаје',
    registrationStats: 'Статистике пријава',
    totalRegistrations: 'Укупно пријава',
    confirmedRegistrations: 'Потврђене пријаве',
    pendingRegistrations: 'Пријаве на чекању',
    waitlistRegistrations: 'Пријаве на листи чекања',
    checkedInCount: 'Пријављено',
    registrationFees: 'Накнаде за пријаву',
    paymentRequired: 'Плаћање потребно',
    paymentPending: 'Плаћање на чекању',
    paymentCompleted: 'Плаћање завршено',
    paymentFailed: 'Плаћање неуспешно',
    noPaymentRequired: 'Плаћање није потребно',
    registrationInstructions: 'Упутства за пријаву',
    registrationInstructionsPlaceholder: 'Молимо прочитајте следећа упутства пре пријаве...',
    dietaryRestrictions: 'Дијететске рестрикције',
    accessibilityNeeds: 'Потребе за приступачношћу',
    emergencyContact: 'Контакт за хитне случајеве',
    emergencyPhone: 'Број телефона за хитне случајеве',
    agreeToTerms: 'Прихватам услове и одредбе',
    termsAndConditions: 'Услови и одредбе',
    privacyPolicy: 'Политика приватности',
    registrationPolicy: 'Политика пријаве',
    refundPolicy: 'Политика повраћаја новца',
    contactOrganizer: 'Контактирај организатора',
    eventOrganizer: 'Организатор догађаја',
    registrationContact: 'Контакт за пријаву',
    registrationEmail: 'Е-маил за пријаву',
    registrationPhone: 'Телефон за пријаву',
    joinWaitlist: 'Придружи се листи чекања',
    eventFullMessage: 'Овај догађај је пуна капацитета. Можете се придружити листи чекања ако је доступна.',
    registrationClosedMessage: 'Пријава за овај догађај је тренутно затворена.',
    backToCalendar: 'Назад на календар',
    confirmCancelRegistration: 'Да ли сте сигурни да желите да откажете вашу пријаву?',
    waitlistPosition: 'Позиција на листи чекања',
    waitlistPositionMessage: 'Ви сте #{position} на листи чекања.',
    checkedInAt: 'Пријављено у {time}',
    paymentStatus: 'Статус плаћања',
    event: 'Догађај',
    searchRegistrations: 'Претражи пријаве...',
    filterByEvent: 'Филтрирај по догађају',
    allEvents: 'Сви догађаји',
    allStatuses: 'Сви статуси',
    noRegistrations: 'Нема пронађених пријава',
    noRegistrationsMessage: 'Нема пријава за догађаје које одговарају вашим тренутним филтерима.',
    moveToWaitlist: 'Премести на листу чекања',
    confirm: 'Потврди',
    confirmDeleteRegistrationMessage: 'Да ли сте сигурни да желите да обришете ову пријаву? Ова акција се не може поништити.',
    manageRegistrationsDescription: 'Управљајте и пратите пријаве за догађаје, пријаве и позиције на листи чекања.'
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    // Get language from URL parameter, localStorage, or default to English
    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search)
      const urlLang = urlParams.get('lang')
      
      if (urlLang && ['en', 'fr', 'sr'].includes(urlLang)) {
        // Update localStorage to match URL
        localStorage.setItem('language', urlLang)
        return urlLang
      }
      
      return localStorage.getItem('language') || 'en'
    }
    return 'en'
  })


  const changeLanguage = (langCode) => {
    setCurrentLanguage(langCode)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', langCode)
      
      // Navigate to current page with new language parameter
      const currentUrl = new URL(window.location.href)
      if (langCode === 'en') {
        // Remove lang parameter for English (default)
        currentUrl.searchParams.delete('lang')
      } else {
        // Add or update lang parameter
        currentUrl.searchParams.set('lang', langCode)
      }
      
      // Navigate to the new URL
      window.location.href = currentUrl.toString()
    }
  }

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key
  }

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    translations,
    availableLanguages: [
      { code: 'en', name: 'English', flag: '🇺🇸' },
      { code: 'fr', name: 'Français', flag: '🇫🇷' },
      { code: 'sr', name: 'Српски', flag: '🇷🇸' }
    ]
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export default LanguageContext
